"""Update region table

Revision ID: 4a1cfe4c9a0e
Revises: 9deb2af671de
Create Date: 2025-04-27 06:35:28.238392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a1cfe4c9a0e'
down_revision: Union[str, None] = '9deb2af671de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(
    ), nullable=False, server_default="Perak"))
    op.add_column('region', sa.Column(
        'emblem_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'emblem_url')
    op.drop_column('region', 'state')
    # ### end Alembic commands ###
